### ISSUE TITLE
docs: update `readme.md` with installation guide (nextjs)

### ISSUE THREAD

**Issue by samyabrata-maji** [samyabrata-maji/next-quickstart#89]
### what's wrong in the documentation?

Create an installation guide for the project to help users get started.

- In the README.md, add a section titled "Installation Guide" with detailed instructions.
- Explain how to clone the repository, install dependencies, and set up any required configuration.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Yasir761** [comment]
Hey, @samyabrata-maji can u assign me these I can issues #91 #88 #88 to me accordingly?

**Comment by samyabrata-maji** [comment]
Sure go ahead!
