### ISSUE TITLE
feat: create toggle button

### ISSUE THREAD

**Issue by samyabrata-maji** [samyabrata-maji/next-quickstart#90]
### What feature?

Right now, the theme button in the menu bar provides three options: dark, light and medium. Replace the menu with a toggle button that will toggle between dark mode and light mode.

### Add screenshots

![Screenshot from 2023-10-03 19-24-31](https://github.com/samyabrata-maji/next-quickstart/assets/116789799/3315b8e7-c2b9-4aca-8c8e-d0b891c8db9d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SaiganeshGurrapu16** [comment]
I am new to open source, I want to work on this issue. Can you assign this to me.

**Comment by princyballabh** [comment]
Hello!
I am a beginner and would like to work on creating the toggle button. Can you please tell about how to get started with this.

**Comment by samyabrata-maji** [comment]
Sorry @Dhoni77 I made a mistake, can you resend the PR.
